name: HelloWorldDotNet Building Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependecies
      run: dotnet restore

    - name: Build for the current platfom
      run: dotnet build -c Release --no-restore      

    - name: Build for Windows X64
      run: dotnet build -c Release -r win-x64     

    - name: List folders
      run: ls -R . -ll

    - name: Run Linux executable
      run: |
        cd ./bin/Release/net8.0
        ./HelloWorldDotNet

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: HelloWorldDotNEt project
        path: ./bin/Release/net8.0/win-x64
